# Generated by Django 5.1.1 on 2026-02-28 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_categorymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(default='', upload_to='subCategory/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.categorymodel')),
            ],
        ),
    ]
