# Generated by Django 5.1.1 on 2026-02-28 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_subcategorymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='', upload_to='product/')),
                ('price', models.BigIntegerField(max_length=10)),
                ('discountType', models.CharField(choices=[('%', '%'), ('Rs', 'Rs')], default='%', max_length=6)),
                ('discount', models.BigIntegerField(max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.categorymodel')),
                ('subCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.subcategorymodel')),
            ],
        ),
    ]
